import Footer from "@/components/Footer";
import Validate from "@/components/global/Validate";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/contexts/AuthProvider";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFont.variable} font-(--font-poppins) antialiased`}
      >
        <ReactQueryProvider>
          <AuthProvider>
            <Header />
            <Toaster position="top-center" />
            <div>{children}</div>
            <Footer />
            <Validate />
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
